service: s3-sqs-lambda

configValidationMode: error

useDotenv: true

provider:
  name: aws
  stage: dev
  runtime: nodejs16.x
  iam:
    role:
      Fn::ImportValue: lambdaRoleArn

functions:
  process:
    handler: src/process.handler
    name: process
    events:
      - sqs:
          arn:
            Fn::ImportValue: coolQueueArn
          functionResponseType: ReportBatchItemFailures
          batchSize: 5
          maximumBatchingWindow: 20

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
