service: s3-sqs-lambda

configValidationMode: error

useDotenv: true

provider:
  name: aws
  stage: dev
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'sqs:ReceiveMessage'
            - sqs:ChangeMessageVisibility
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            - sqs:GetQueueUrl
          Resource: '*' # Don't do this, instead you can put the sqs arn or some part of it

functions:
  process:
    handler: src/process.handler
    name: process

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: true
    exclude:
      - aws-sdk
